services:
  mysql_stage:
    image: mysql:latest
    container_name: mysql_curso
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'base_stage'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'teste'
      MYSQL_USER: 'teste'
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"  # Mapeia a porta 3306 do host para a porta 3306 do contêiner MySQL
    networks:
      - rede_internal

  rabbit:
    build:
      context: .
      dockerfile: Dockerfile-habbitMQ
    container_name: HabbitMQ
    restart: always
    volumes:
      - ./confHabbitMq:/etc/rabbitmq/rabbitmq.config
    ports:
      - 8080:15672
      - 5672:5672
    networks:
      - rede_internal

networks:
  rede_internal:
    driver: bridge  # Ou o driver que você preferir
